### PR TITLE
Add global:delete

### PR DESCRIPTION
**Pull request by forgee**
Fix small grammar mistake in documentation

### CODE REVIEW

**Comment by Raggaer** [comment]
I am not sure if deleting something that does not exist doesnt return an error

**Comment by forgee** [comment]
It does not.

**Comment by Raggaer** [comment]
Sorry. I edited the previous post.

I am not sure if deleting something that does not exist doesnt return an error

Have you checked that this does not occur?

**Comment by forgee** [comment]
I edited my post aswell. There is no error when the key doesn't exist and all is working fine.

**Pull request merged**
